services:
  - type: web
    name: visual-api-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn visual_api_designer.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: visual-api-db
    databaseName: visual_api_db
    user: visual_api_user