# Generated by Django 5.2.6 on 2025-09-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('lifestyle', 'Lifestyle'), ('education', 'Education'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', help_text='Choose a category for your post', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short description of the post (auto-generated if empty)', max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='blog_post_categor_ded810_idx'), models.Index(fields=['created_at'], name='blog_post_created_b20a1e_idx'), models.Index(fields=['is_published'], name='blog_post_is_publ_96cac2_idx')],
            },
        ),
    ]
