# Generated by Django 5.2.6 on 2025-09-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_categor_ded810_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_created_b20a1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_is_publ_96cac2_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('design', 'Design'), ('business', 'Business'), ('lifestyle', 'Lifestyle'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
